### ISSUE TITLE
🗄🔧 Loopback 3.0

### ISSUE THREAD

**Issue by paulcedrick** [gothinkster/realworld#105]
# Current Status

**Codebase in progress:**
[paulcedrick/realworld-loopback](https://github.com/paulcedrick/realworld-starter-kit)

**Interested in helping out? [Join us in gitter](https://gitter.im/Realworld-loopback/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) :tada:**

## Todo:

 - [x] :checkered_flag: Fork the starter repo & post the link in this issue
 - [x] :art: Create logo for repo & update issue status (@ericsimons)
 - [ ] :hammer: Implement all of Conduit's functionality per the spec & API
 - [ ] :eyes: Move repo to main org & Peer review final codebase by admins/community (RFC)
 - [ ] :tada: Tag v1 release and officially list it on the README!

**Comment by beeman** [comment]
Hey @paulcedrick, I would like to help out with this project!

**Comment by paulcedrick** [comment]
Hi @beeman ! Awesome! :) That will be great. :) I actually just created this -> https://gitter.im/Realworld-loopback/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link so that we can interact with those who want to help us in doing this one. :+1: :tada:

**Comment by AngelsProjects** [comment]
Are you going to make a real world app with loopback v4?

**Comment by AngelsProjects** [comment]
is there somebody working on this? if not i can wok but in loopback v4

**Comment by gfernandes410** [comment]
The last commit of @paulcedrick in the repo was 3 years a go. Let's start it in loopback 4?

**Comment by paulcedrick** [comment]
Hi @AngelsProjects and @gfernandes410 , sure! if you guys want to start in loopback 4, let's create a new one and i'll be willing to contribute to it

**Comment by AngelsProjects** [comment]
Great! Let's do this.

**Comment by paulcedrick** [comment]
@AngelsProjects let me know once you created new repo for it. :)

**Comment by achrinza** [comment]
Hi, any updates on this? I'd like to contribute if possible :)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
