### ISSUE TITLE
🗄 🔧 Crystal + Kemal

### ISSUE THREAD

**Issue by humboldtux** [gothinkster/realworld#112]
# Current Status

### Todo:

- [x]  :checkered_flag: Fork the starter repo & post the link in this issue
- [ ]  :art: Create logo for repo & update issue status (@ericsimons)
- [ ]  :hammer: Implement all of Conduit's functionality per the spec & API
- [ ]  :eyes: Peer review of final codebase by RealWorld admins & community (RFC)
- [ ]  :tada: Tag v1 release, move repo to main org, and officially list it on the README!

--------------------------------------------------------------------------------

I would like to work on this

**Comment by EricSimons** [comment]
Woot! Can't wait to see this @humboldtux 👍

**Comment by reiswindy** [comment]
Hi, I'm interested in continuing this project. I've been trying to contact the original author for days but haven't received any response, and the project has been inactive for almost a year. I currently have a fork of it with most (if not all) of the implementation of Conduit's functionality (https://github.com/reiswindy/kemal-realworld).

**Comment by Cameron-C-Chapman** [comment]
Sounds good @reiswindy. Just let us know here when you are ready to have it reviewed and added and we'll get you added to the main readme.

**Comment by alexanderadam** [comment]
@reiswindy thank you for your efforts! Any news?

**Comment by reiswindy** [comment]
Hi. The implementation was finished but I got stuck while writing the readme and tests (currently there's no tests, and readme is lacking). Right now the repo needs updating because Crystal had many releases since then (0.24.0 -> 0.33.0), some breaking-changes need to be fixed.

**Comment by reiswindy** [comment]
Repository has been updated and the breaking-changes have been fixed. 

#### Todo:
* [x] :checkered_flag: Fork the starter repo & post the link in this issue
* [x] :art: Create logo for repo & update issue status
* [x] :hammer: Implement all of Conduit's functionality per the spec & API
* [ ] :eyes: Peer review of final codebase by RealWorld admins & community (RFC)
* [ ] :tada: Tag v1 release, move repo to main org, and officially list it on the README!
