### ISSUE TITLE
Preact

### ISSUE THREAD

**Issue by hassanbazzi** [gothinkster/realworld#169]
## Current Status
Codebase in progress: [Codebase](https://github.com/hassanbazzi/preact-realworld-example-app)

Interested in helping out? Say hello! 🎉 [Preact Slack](https://preact-slack.now.sh/)

## Todo:
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

I have began working on this. :) I will most likely be using [unistore](https://github.com/developit/unistore) for state. And sine Preact is all about performance and low file size, I'm going to see if I can shrink down the styles provided by the project.

**Comment by quanla** [comment]
Hi @hassanbazzi, the developers of this project seem to be very unresponsive. I also have an implementation in issue #161, which is using only React (no Redux or MobX) so the code size is pretty small. I guess that if I use Preact, the code base will be very similar. We can trade thought. Cheers

**Comment by chimon2000** [comment]
Is this still being worked on @hassanbazzi

**Comment by hassanbazzi** [comment]
I dropped it at the time given the repo/ peoject seemed to go stale.

**Comment by mutoe** [comment]
Hello, I recently implemented Realworld with Preact X.

If the original author doesn't have any updates, I would like to submit a PR and close the Issue.

Here is the project address: https://github.com/mutoe/preact-realworld-example-app

**Comment by anishkny** [comment]
Great job @mutoe!

Found a couple of bugs - could you please fix them - that would be awesome!

Blocked by: https://github.com/mutoe/preact-realworld-example-app/issues/1

**Comment by mutoe** [comment]
> Great job @mutoe!
> 
> Found a couple of bugs - could you please fix them - that would be awesome!
> 
> Blocked by: [mutoe/preact-realworld-example-app#1](https://github.com/mutoe/preact-realworld-example-app/issues/1)

@anishkny  I have fixed these bugs, could you please have a look again? thank you

[Online preview](https://preact-realworld.mutoe.com)
