### ISSUE TITLE
Cyclejs

### ISSUE THREAD

**Issue by AnaRobynn** [gothinkster/realworld#179]
# Current Status
## Codebase in progress:
[Cyclejs](https://github.com/AnaRobynn/cyclejs-realworld-example-app)

## Interested in helping out? Come say hello! 🎉
Cycle.js sparked my interest after working with Angular 2 + RxJS and React. I loved playing around with streams in RxJS and love how declarative React is, but I wanted to try out a more functional approach. I have no prior experience with Cycle.js, I hope that's ok.

## Todo
- [x]  🏁 Fork the starter repo & post the link in this issue
- [ ]  🎨 Create logo for repo
- [ ]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]   👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ]  🎉 Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by AnaRobynn** [comment]
I'm unable to work on it, since priorities changed.
