### ISSUE TITLE
Fullstack Firebase

### ISSUE THREAD

**Issue by doowb** [gothinkster/realworld#199]
# Current Status

## Codebase in progress:
[doowb/firebase-realworld-example-app](https://github.com/doowb/firebase-realworld-example-app)

## Todo:
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

**Comment by doowb** [comment]
Based on my comments in #21 I forked the starter kit to start on creating a "fullstack" firebase realworld example app.

There are some issues discussing using React with Firebase so I'll go down that path for now. Once that is down and the data model is fleshed out, I'd be happy to do the same for other front-ends since I'm using this as a way to learn more about front-end frameworks.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
