### ISSUE TITLE
🗄🔧 Laravel

### ISSUE THREAD

**Issue by unicodeveloper** [gothinkster/realworld#20]
# Current Status

- ### Codebase functionality complete! RFC is now open:<br /> [gothinkster/laravel-realworld-example-app](https://github.com/gothinkster/laravel-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/laravel](https://gitter.im/realworld-dev/laravel)**

### Todo:

- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

I would love to work on this!

**Comment by lincolnbrito** [comment]
+1
I'm too!

**Comment by EricSimons** [comment]
@unicodeveloper @lincolnbrito Awesome — lets get this started! Can one of you [fork our starter kit](https://github.com/gothinkster/realworld-starter-kit) and post the link in this issue? I also created a logo that you can use for the readme:


![laravel-realworld-logo](https://cloud.githubusercontent.com/assets/556934/25306200/81705610-273d-11e7-8a2b-a00b336c3a40.png)

**Comment by EricSimons** [comment]
Just set up [**the Gitter chatroom**](https://gitter.im/realworld-dev/laravel) for this! Lets do our collaborator coordination in there 👍

cc/ @unicodeveloper @lincolnbrito

**Comment by Hasnayeen** [comment]
@EricSimons I've setup a repo for this
https://github.com/iluminar/laravel-realworld-example-app

**Comment by Hasnayeen** [comment]
Task list categorized by api

- [ ] Articles
  - [ ] GET - Feed
  - [ ] GET - All articles
  - [ ] GET - Articles by author
  - [ ] GET - Articles favorited by username
  - [ ] GET - Articles by tag
  - [ ] POST - Create article
  - [ ] GET - Single article by slug
  - [ ] DEL - Delete article
  - [ ] PUT - Update article
  - [ ] POST - Favorite article
  - [ ] DEL - Unfavorite article

- [ ] Auth
  - [ ] POST - Login
  - [ ] POST - Login and remember token
  - [ ] POST - Register
  - [ ] GET - Get current user
  - [ ] PUT - Update user

- [ ] Comments
  - [ ] GET - All comments for article
  - [ ] POST - Create comment for article
  - [ ] DEL - Delete comment

- [ ] Profile
  - [ ] GET - Profile
  - [ ] POST - Follow profile
  - [ ] DEL - Unfollow profile

- [ ] Tags
  - [ ] GET - Get all tags

**Comment by Hasnayeen** [comment]
I'm working on Register and Login api

**Comment by MattMangoni** [comment]
If nobody's already working on it, I'll take care of the articles API

**Comment by SandeeshS** [comment]
So I took the liberty to finish this myself from scratch, since I had some time on my hand and wanted to start making contributions to the open source community :)

I've updated and cleaned up the repo. The latest code can be found below. I've added clear documentation throughout the code. The only thing pending is updating the read me with instructions and info related to code.
https://github.com/SandeeshS/laravel-realworld-example-app

I want to know if we can create a new PR for the laravel backend and point to this. Since contributors can easily find and work on this repo, or we clean up this PR and continue here. I'll wait for reviews from fellow members before finalising the code changes and then tag v1. Appreciate any feedback.

**Comment by EricSimons** [comment]
@SandeeshS holy smokes! Nice work!!! 

@Hasnayeen @unicodeveloper @MattMangoni can you guys take a look at the repo @SandeeshS made and lmk if I can update the status to point at that?

**Comment by Hasnayeen** [comment]
@EricSimons , yes, I think that would be a good idea

**Comment by SandeeshS** [comment]
Well looks like the laravel section is really lacking contributors.

I've added complete model factories and a full configurable database seeder. So anyone can just run the seeder and have a ready server populated with data, including all the relationships. This will be very useful for users testing the api or trying to couple the frontend.

The readme is updated with the complete instructions and information regarding the app. I'm gonna couple a frontend on my local server and perform few final tests and then tag v1 for use.

@EricSimons can you please change the main comment to reflect the repo changes and the task list. Also all the task list mentioned in https://github.com/gothinkster/realworld/issues/20#issuecomment-296448431 are complete.

**Comment by EricSimons** [comment]
@SandeeshS just cloned your repo and put it under the main org + added you to it!

Lets get the RFC opened up on this thing — does anyone know folks on the core Laravel team/community that could come provide feedback?

**Comment by unicodeveloper** [comment]
@EricSimons I have taken my time to go through the source code and I can comfortably say that this is SOLID! @SandeeshS did a great job!!!

**Comment by SandeeshS** [comment]
@unicodeveloper thank you. The code base has been updated with cors and some more changes and should be set. We'll wait for a review like @EricSimons says before tagging a main release. Meanwhile i'll be taking any issues or PR and keep things in check. Next on the list is adding tests. If someone wants to then they can go forward and do it, if not i'll work on it once i get some time on my hand.

**Comment by SandeeshS** [comment]
@EricSimons anyway we can push the completed backend on the main page? I'd consider @unicodeveloper as a good peer for the review judging by his background in the laravel community. You guys could do a test run with a local setup to verify the api, there's clear instructions.

**Comment by EricSimons** [comment]
@SandeeshS absolutely — I just need to change the layout/design of the readme to be able to accommodate this + upcoming stacks  :) Will have this listed there by EOD. Great job! 💯

**Comment by brwr** [comment]
Since this has been moved to the GoThinkster org, I vote that we close this issue. All future conversation should happen in [gothinkster/laravel-realworld-example-app](https://github.com/gothinkster/laravel-realworld-example-app) unless it's application to the RealWorld project at large.

**Comment by EricSimons** [comment]
Agreed — closing this issue 👍
