### ISSUE TITLE
🖥 🔧 Ember

### ISSUE THREAD

**Issue by Alonski** [gothinkster/realworld#22]
# Current Status

- ### Codebase in progress:<br /> [github.com/gothinkster/ember-realworld](https://github.com/gothinkster/ember-realworld)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/ember](https://gitter.im/realworld-dev/ember)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

-----

I am planning to start working on this 😄 
Check it out: https://github.com/gothinkster/ember-realworld

**Comment by EricSimons** [comment]
Awesome! I just created custom logo that you can use for the readme:

![ember-realworld-logo](https://cloud.githubusercontent.com/assets/556934/25306472/85c50a62-2742-11e7-872d-00184a4dda1c.png)

**Comment by Alonski** [comment]
Cool thanks! Update the readme

**Comment by alexlafroscia** [comment]
Hey, I'd be interested in helping out with the Ember app. Let me know if there's anything I can do @Alonski

**Comment by EricSimons** [comment]
Just set up [**the Gitter chatroom**](https://gitter.im/realworld-dev/ember) for this project — lets do our collaborator coordination in there 👍

cc/ @Alonski @alexlafroscia

**Comment by snewcomer** [comment]
Would ya'll mind if I hopped on the github ember app to bring it across the finish line?

**Comment by Alonski** [comment]
Hey man @snewcomer, I would love some help :) I will be happy to review any pull requests. Thanks

**Comment by Cameron-C-Chapman** [comment]
Hi @Alonski, @snewcomer 😄 Is this branch still active? We're trying to clean up the open issues a bit. If you're still planning on knocking this out no problem keeping it open, but if you've moved on maybe we change the status to seeking engineers or close it? What do you think?

**Comment by snewcomer** [comment]
I have this PR out there.  I'll work on updating this Friday and ping you when it is done!

https://github.com/gothinkster/ember-realworld/pull/30

**Comment by Alonski** [comment]
@Cameron-C-Chapman I would like to continue working on this and thanks for the update.
@snewcomer Lets try to have a chat sometime soon over how to get this implementation done?

Finding time for projects like these is hard 😄

**Comment by Cameron-C-Chapman** [comment]
Sounds good @Alonski 😄

**Comment by MelSumner** [comment]
@danilovaz ping me on Discord, happy to provide whatever information is helpful! :+1:

**Comment by Alonski** [comment]
@danilovaz Life is exciting :) I'd love help if you're willing. I'm on Discord `@alon`

**Comment by AhHa45** [comment]
whats the status guys? :)

**Comment by Alonski** [comment]
@AhHa45 this is about half done. I'm doing this in my, non existent, free time so this hasn't moved in a while. I'd love some help. Hit me up on Discord.

**Comment by QuantumInformation** [comment]
Glad this got started, Ember deserves a place in here!

**Comment by Alonski** [comment]
Thanks @QuantumInformation Still need help getting this to completion 😁

**Comment by NullVoxPopuli** [comment]
How much is involved with setting this up? Would love to do an octane version

**Comment by mansona** [comment]
@NullVoxPopuli just to let you know there is already an octane version that is completed 👍 I'll ask the author if he's happy to post the link here but I think the plan is to finish the Classic and release them both at the same time.

**Comment by delusioninabox** [comment]
Is there any help still needed on the Classic version? I have some time this month and next.

**Comment by Alonski** [comment]
@delusioninabox yes! You are always welcome! If you want to ping me on Discord we can chat about it

**Comment by QuantumInformation** [comment]
Looking fwd to the octane version!

**Comment by Alonski** [comment]
@patocallaghan

**Comment by Alonski** [comment]
@anishkny I am not sure if you are still maintaining this or not.
We think that we finally finished everything and are up to spec :)
Can we become official please?

**Comment by anishkny** [comment]
Sorry for the delay - should be added soon.

**Comment by Alonski** [comment]
Awesome can't wait!
