### ISSUE TITLE
🗄🔧 Rust

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#24]
# Current Status

- ### Codebase in progress:<br /> [hsharpsoftware/rust-realworld-example-app](https://github.com/hsharpsoftware/rust-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/rust](https://gitter.im/realworld-dev/rust)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [x] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [x] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

----

**Comment by davidpodhola** [comment]
Is there already a repo somewhere or should I create one?

**Comment by EricSimons** [comment]
@davidpodhola nope! Go ahead and fork the starter kit & then post the link to your repo back here 👍

**Comment by davidpodhola** [comment]
Create a [repo](https://github.com/hsharpsoftware/rust-realworld-example-app).

**Comment by brwr** [comment]
I added the repo status to this issue and created the Gitter channel. All information is at the top of the page. :+1:

**Comment by EricSimons** [comment]
@davidpodhola just created a logo that you can use for the readme in your repo!

![rust](https://cloud.githubusercontent.com/assets/556934/25449146/7a1c5dd2-2a80-11e7-90d1-0e0886db070a.png)

**Comment by davidpodhola** [comment]
thanks, logo updated.

**Comment by petermbenjamin** [comment]
@davidpodhola - do you intend to make use of [Diesel](http://diesel.rs/)?

**Comment by davidpodhola** [comment]
Thanks for bringing this up @petermbenjamin.

Since I have the most experience with Microsoft SQL, the current repository is using [tiberius ](https://github.com/hsharpsoftware/rust-realworld-example-app/blob/master/server/Cargo.toml#L15).

I think we can also use different databases or ORMs with conditional compilation.

**Comment by davidpodhola** [comment]
I think  all of Conduit's functionality is implemented, please have a look and let me know.

**Comment by EricSimons** [comment]
Just created created new repo & added you to it @davidpodhola — rust is now listed in the readme! Excellent work! 💯  I can't wait to dig into this codebase :)
