### ISSUE TITLE
ASP.NET Core Using Functional Programming with C#

### ISSUE THREAD

**Issue by dnikolovv** [gothinkster/realworld#270]
# Current Status

- https://github.com/dnikolovv/dev-adventures-realworld

![postman-tests](https://devadventures.net/wp-content/uploads/2018/09/conduit-tests.png)

![newman-tests](https://devadventures.net/wp-content/uploads/2018/10/newman-passing.png)

# Todo:

- [x]  🏁 Fork the starter repo & post the link in this issue
- [x]  🔨 Implement all of Conduit's functionality per the spec & API
- [x]  💬 Complete the README file
- [x]  🎨 Create logo for repo & update issue status (@EricSimons )
- [x]  👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ]  🎉 Tag v1 release, move repo to main org, and officially list it on the README!

# Get involved!

Help increase the test coverage. [dnikolovv/dev-adventures-realworld/tests](https://github.com/dnikolovv/dev-adventures-realworld/tree/master/tests/Conduit.Business.Tests)
Complete issues via Pull Requests or more add issues! [dnikolovv/dev-adventures-realworld/issues](https://github.com/dnikolovv/dev-adventures-realworld/issues)

# Background

This was done as there are very few examples of real applications written using functional C# and this can serve as a general guideline. The overall architecture is taken from the [Dev Adventures .NET Core template](https://marketplace.visualstudio.com/items?itemName=dnikolovv.dev-adventures-project-setup).

I am aware of [Adam Hathcock's .NET Core implementation](https://github.com/adamhathcock/realworld-aspnetcore-kit) and I think it is great, but the differences between the two are so significant that they should be viewed upon as completely different implementations.

**Comment by dnikolovv** [comment]
You're definitely right! I'll take up on that soon.

**Comment by dmytrohridin** [comment]
@lastlink @dnikolovv ther is already repository for Nancy and issue
https://github.com/gothinkster/realworld/issues/123

By the way @dnikolovv your implementation is very excited!

**Comment by dnikolovv** [comment]
Hey @anishkny. Since all tests are passing now, may we move this one into a "review" stage?

**Comment by anishkny** [comment]
@dnikolovv would it be possible have build/test setup in something like [TravisCI](https://docs.travis-ci.com/user/languages/csharp/) or [AppVeyor](https://www.appveyor.com/docs/build-configuration/)?

**Comment by dnikolovv** [comment]
@anishkny Of course! I've added TravisCI.

**Comment by dnikolovv** [comment]
Hey guys,

It's been a few months now. I've set the Travis build to run the Postman tests and everything appears to be working correctly. Do you think we should be moving this one into the official Readme?

**Comment by anishkny** [comment]
@dnikolovv looks good to me. Great work. Do you want to send a PR adding your repo to: [`etc/backend-repos.yaml`](https://github.com/gothinkster/realworld/blob/master/etc/backend-repos.yaml). Thanks!

**Comment by lastlink** [comment]
I think that this may have the issues that many other WIP have and are missing, updating an article & tags.

**Comment by dnikolovv** [comment]
@lastlink Updating an article together with its tags works as intended. Are there any other "tricky" parts that I could check?

@anishkny I've submitted a PR.

**Comment by anishkny** [comment]
Added
