### ISSUE TITLE
Meta: Lambda (All Languages) + DynamoDB  [Backend]

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#30]
# Current status

- [x] Node Lambda + DD: **https://github.com/gothinkster/realworld/issues/37 WIP**
- [ ] Python Lambda + DD: _Seeking Engineers!_
- [ ] Java Lambda + DD: _Seeking Engineers!_
- [ ] C# Lambda + DD: _Seeking Engineers!_
-----

Similar to #21, it would be interesting to try and implement the backend using just AWS DynamoDB and Lambda functions. Something like [serverless](https://serverless.com) could be used to quickly scaffold the requisite API.

**Comment by EricSimons** [comment]
Lambda+Dynamo would be super cool — you down to lead this one as well? I've been really digging your code quality for the GCP version 👌

**Comment by brwr** [comment]
Something to consider: Lambda supports Node, Java, Python, and C#. It would be worth having each of these supported (with their respective serverless-like libraries) as we see an interest.

**Comment by EricSimons** [comment]
^ thats a cool idea. Do you think we should have a common "serverless spec" to share between them? Or just let the devs implement in their desired way?

**Comment by anishkny** [comment]
+1 for Lambdas in all supported languages.

I can take a stab at DD+Lambda NodeJS using [serverless](https://github.com/serverless/serverless). Spun off [repo](https://github.com/anishkny/realworld-dynamodb-lambda).

Note: I can't fork the starter repo twice from my account, so I manually forked it (by cloning locally, and pushing to new remote). So it wont show up in the official starter kit's [fork graph](https://github.com/gothinkster/realworld-starter-kit/network).

**Comment by EricSimons** [comment]
No sweat on the fork count for the starter kit, we only created it just so that getting started could (_potentially_) be as easy as one click :)

I'm going to create a separate issue for the Node DD+Lambda stack, and I'll put a checklist in this one for the remaining languages we'd like to support 👍

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
