### ISSUE TITLE
Server-Side Blazor

### ISSUE THREAD

**Issue by burke166** [gothinkster/realworld#366]
# Current Status

* codebase in progress: [https://github.com/burke166/blazor-server-side-realworld-example-app](https://github.com/burke166/blazor-server-side-realworld-example-app)
* demo: [https://blazorserverside.computercodeblue.com/](https://blazorserverside.computercodeblue.com/)

This has a lot in common with [torhovland/blazor-realworld-example-app](https://github.com/torhovland/blazor-realworld-example-app), but Razor Components seems to be different enough from Blazor that I didn't fork directly from that.

# TODO
* [x]  🏁 Fork the starter repo & post the link in this issue
* [ ]  🎨 Create logo for repo & update issue status (@EricSimons)
* [x]  🔨 Implement all of Conduit's functionality per the spec & API
* [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
* [ ]  🎉 Tag v1 release and officially list it on the README!

**Comment by burke166** [comment]
With .NET Core 3 Preview 4, Microsoft is back to calling it Server-Side Blazor rather than Razor Components. Working on the update to convert from Preview 3 to Preview 4.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
