### ISSUE TITLE
🗄🔧 Node.js Lambda + DynamoDB

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#37]
# Current Status

- ### Codebase in progress:<br /> [anishkny/realworld-dynamodb-lambda](https://github.com/anishkny/realworld-dynamodb-lambda)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/node-lambda-dynamodb](https://gitter.im/realworld-dev/node-lambda-dynamodb)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

-----

Thanks @anishkny for taking lead on this! 🍻

**Comment by sluongng** [comment]
Is this active?

**Comment by anishkny** [comment]
@sluongng I am actually looking for collaborators. Care to help out?

I am thinking of using [AWS SAM](https://github.com/awslabs/serverless-application-model) to implement the app.

**Comment by sluongng** [comment]
@anishkny I planned to contribute earlier. However, Im pretty busy for the next few weeks or so. 

I would suggest you consider [Serverless Framework](https://github.com/serverless) instead. The community over there is well established with plugins for ES2016 and TypeScript which might be great for educational purposes. AWS SAM seems to be trying to catch up to Serverless Framework but it has far way to go

**Comment by anishkny** [comment]
@sluongng no worries.

Actually, currently the project **is** using Serverless Framework (see [YAML file](https://github.com/anishkny/realworld-dynamodb-lambda/blob/master/serverless.yml)) and we can totally continue to use that.

**Comment by anishkny** [comment]
This project is being [actively worked on](https://github.com/anishkny/realworld-dynamodb-lambda/graphs/contributors)

**Comment by anishkny** [comment]
V1 functionality is complete 🎉

@Cameron-C-Chapman would you mind kicking around the [tires](https://github.com/anishkny/realworld-dynamodb-lambda)?

**Comment by Cameron-C-Chapman** [comment]
This looks amazing @anishkny!

I'm getting an error about an invalid cookie. Do you know why and/or how to remedy that?

I tried to POST a new user and get all articles and got the same error.

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Invalid cookie value"
}
```

**Comment by anishkny** [comment]
Thanks for trying it out @Cameron-C-Chapman. Do you have exact repro steps? Were you using curl/Postman? Was it localhost?

**Comment by anishkny** [comment]
Thanks for the docs fix. Yeah I have seen weird cookie behavior in Postman before. Closed by #248
