### ISSUE TITLE
📱🔧 Jasonette

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#39]
# Current Status

- ### Codebase in progress:<br /> [anishkny/realworld-jasonette](https://github.com/anishkny/realworld-jasonette)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-jasonette/Lobby](https://gitter.im/realworld-jasonette/Lobby)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

### Background:

[Jasonette](http://jasonette.com) is a radical new way to develop **native** Android/iOS apps using just **JSON**... yes you heard me right!

The entire app is specified by a single JSON object, served over HTTP, which is then hydrated on the fly for a native mobile experience.

It would be cool to see RealWorld implemented using Jasonette!

Perhaps @gliechtenstein would be up for the task?

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
