### ISSUE TITLE
📱🔧 Swift

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#43]
# Current Status

- ### Codebase in progress:<br /> [littleStudent/swift-realworld-example](https://github.com/littleStudent/swift-realworld-example)
- ### Interested in helping out? Say hello! 🎉 <br />

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Would be really cool to see a native iOS Conduit app <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_emojione_64.png);background-position:10% 25%;background-size:4100%"></span></span>

Any Swifters out there that wanna take this one?

**Comment by littleStudent** [comment]
hey @EricSimons. Here is the fork for the swift example https://github.com/littleStudent/swift-realworld-example
I will try to get a version with the global feed out in the next few days, so I can gather some feedback on the codebase.

**Comment by SandeeshS** [comment]
I've updated the status and added your repo :+1:

**Comment by amadeu01** [comment]
Hi, I noticed that the repository of [littleStudent/swift-realworld-example](https://github.com/littleStudent/swift-realworld-example) have not moved. So, I create a repository to implement the codebase for iOS in Swift  😄 

here is the link [amadeu01/swift-realworld-conduit](https://github.com/amadeu01/swift-realworld-conduit)

**Comment by HassanElDesouky** [comment]
Hi, I still new to open source and I would love to help you. Is there any way that I can help? 

Thanks 😊

**Comment by M1zz** [comment]
hello!

**Comment by jonator** [comment]
Any intention of using swiftui??

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
