### ISSUE TITLE
📱🔧 Java/Android

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#44]
# Current Status

### Todo:

- [ ] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Would be really cool to see a native Android Conduit app ❤️

Any Android folks out there that wanna take this one?

**Comment by dalgarins** [comment]
Hi, I want to help, with this real code example.

**Comment by dalgarins** [comment]
https://github.com/dalgarins/realworld-starter-kit

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
