### ISSUE TITLE
Fullstack .NET Core + Blazor

### ISSUE THREAD

**Issue by JoeyMckenzie** [gothinkster/realworld#462]
Been working on this for a few months off and on, with the intention of implementing the front and backends entirely in C# based frameworks, and I’m currently in the process of updating the backend to .NET Core 3.1 and it shares similarities in approaches taken by the two ranked .NET Core solutions. My intention is to implement a server side Blazor project using Fluxor for redux. Inspiration also comes from the clean architecture Northwond Traders demo: https://github.com/JasonGT/NorthwindTraders/tree/master

I think it would be neat to show the power of fullstack .NET Core to anyone interested in wanting to build applications using C# almost entirely.

## Current Status
**Codebase** WIP - https://github.com/joey32793/realword-dotnet-clean-architecture
**Demo** - WIP, plan is to Dockerize and deploy to Azure

## Todo:

- [x] 🏁 Fork the starter repo & post the link in this issue
- [ ] 🎨 Create logo for repo
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by Chibuikekenneth** [comment]
Are you still working on this @joey32793 ??

**Comment by joey32793** [comment]
@Chibuikekenneth Not currently, and I'm not sure if I plan on doing any updating here in the near future. If I find the time, the plan is to update all projects to .NET Core 3 and add a Blazor frontend.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
