### ISSUE TITLE
🖥 🔧 Relay

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#48]
# Current Status

### Todo:

- [ ] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Originally from https://github.com/gothinkster/realworld/issues/6

**Comment by steveluscher** [comment]
I'll chip away at https://github.com/steveluscher/relay-realworld-example-app. I tentatively chose not to put ‘modern’ in the repo name. Someone can always make a relay-**classic**-realworld-example-app repo to distinguish it from this one.

**Comment by steveluscher** [comment]
It's been 5 months that I've been sitting on this issue without making any progress. I should most certainly step aside so that another interested person with the time to see it through can step in!

I've deleted the repo that I forked. @EricSimons, would you mind modifying the description of this issue to set it back to ‘looking for contributor(s)’ status?

**Comment by EricSimons** [comment]
Done!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
