### ISSUE TITLE
🗄🔧 Flask

### ISSUE THREAD

**Issue by a-r-g-v** [gothinkster/realworld#51]
# Current Status

- ### Codebase in progress:<br /> [a-r-g-v/realworld-flask](https://github.com/a-r-g-v/realworld-flask)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/flask](https://gitter.im/realworld-dev/flask)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [x] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by EricSimons** [comment]
Awesome! Just updated the issue status, created [a gitter room](https://gitter.im/realworld-dev/flask) for us to manage collaborator coordination, and created the logo for your repo's readme 👍:

![flask](https://cloud.githubusercontent.com/assets/556934/25392886/c68d5d8a-298e-11e7-97c6-5b9ed1c26daf.png)

**Comment by EricSimons** [comment]
@alanhamlett would you be interested in helping out @a-r-g-v with this? :)

**Comment by alanhamlett** [comment]
Yea I can help 👍

**Comment by 1755** [comment]
I'll try to help too ☺️

**Comment by 1755** [comment]
I have several questions:
1. There are any limitations for using packages or I can use any ones?
2. What steps should I to do for make contribution? Fork repo, implement backend and made pull request after everything will be ready?

**Comment by EricSimons** [comment]
@a-r-g-v just making sure you saw @1755's comments above :)

**Comment by a-r-g-v** [comment]
@1755 
Sorry, I was so busy that I could not replay you.
1. You can use any package you think best thing. 
2. Please do that way.

**Comment by 1755** [comment]
@a-r-g-v I see. Thanks for reply :)

**Comment by mohamed-aziz** [comment]
Hello, I completed work here,

mohamed-aziz/flask

If the codebase you are working on now is chosen, could you please reference to my repo as an alternative implementation, Thanks.

Also can I add the logo to my repo?

**Comment by mohamed-aziz** [comment]
Also can someone review the code?

**Comment by EricSimons** [comment]
@a-r-g-v @mohamed-aziz just saw the convo in the Gitter room + these comments! Are we going to use @a-r-g-v as the main version?

**Comment by SandeeshS** [comment]
Closing this as it's complete and repo moved here https://github.com/gothinkster/flask-realworld-example-app
