### ISSUE TITLE
[Frontend] elm-spa

### ISSUE THREAD

**Issue by ryannhg** [gothinkster/realworld#541]
### Hey folks!

I'm the creator of [elm-spa](https://elm-spa.dev), a framework for building web applications with the [Elm](https://elm-lang.org) programming language.

I just created a RealWorld example application and wanted to share it here!

Let me know if there's anything you need from me.

**Thanks! 😄** 

### Current Status
Codebase: https://github.com/ryannhg/elm-spa-realworld
Demo: https://realworld.elm-spa.dev/

### Todo:
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by kashifimran** [comment]
@ryannhg Thank for you sharing this. I just checked it out. Looks great. I am curious how much effort it was in terms of man hours? Could you pleas shed some light on it? Thank you.

**Comment by ryannhg** [comment]
Hey @kashifimran it took approximately 16 hours to create the entire app.

There's a bit more detail in my blog post:
https://rhg.dev/posts/realworld-elm-spa

**Comment by kashifimran** [comment]
@ryannhg Thanks a lot for the valuable information. I am trying to find out how much a framework affects this particular need, as for small-medium apps, budget + time are very important consideration.

Much appreciated.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
