### ISSUE TITLE
🗄🔧 Clojure

### ISSUE THREAD

**Issue by sio-iago** [gothinkster/realworld#57]
# Current Status

- ### @sio-iago will be taking lead on this!

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Any interest on having a Clojure + CSP + ring backend? If so, please let me know!

**Comment by EricSimons** [comment]
Yup! 👋 Feel free to fork the starter kit and get started (& post the link to your repo on this issue and I'll update the issue status, etc tomorrow AM)

**Comment by roman01la** [comment]
Hey! I'd like to work on ClojureScript front-end. @EricSimons Should I open a separate issue?

**Comment by EricSimons** [comment]
@roman01la yes for sure! Feel free to open a new issue & fork the starter kit 👍 Looking fwd to seeing it!

**Comment by roman01la** [comment]
@EricSimons Nice! Already working on it 🙃

**Comment by sio-iago** [comment]
Cloned @ https://github.com/sio-iago/realworld-starter-kit/

**Comment by jablub** [comment]
@sio-iago Is this finished?

**Comment by SandeeshS** [comment]
@sio-iago Guess this was never completed. You can check the current code base at https://github.com/sio-iago/realworld-starter-kit

**Comment by jablub** [comment]
@SandeeshS It "looks" finished. I cloned and got it up and running and then ran the postman test suite against it, which worked fine against the public api. It seems thought that the test suite assumes some initial dataset, is that correct? If so do you have any way of testing the backend implementations?

**Comment by sio-iago** [comment]
The user endpoints are working. But I still didn't have time to finish the other ones.

**Comment by myguidingstar** [comment]
Hi all, I have a nearly complete implementation here. Progress is reported in project's github issues.
https://github.com/walkable-server/realworld

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
