### ISSUE TITLE
🗄🔧 Nim

### ISSUE THREAD

**Issue by battila7** [gothinkster/realworld#60]
# Current Status

- ### @battila7 will be taking lead on this!

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

If I have the time on the weekend, I'll start the implementation in [Nim](https://nim-lang.org/) and then update this issue accordingly. 
Not decided yet, whether to use [Jester ](https://github.com/dom96/jester) or [Rosencrantz](https://github.com/andreaferretti/rosencrantz).

**Comment by EricSimons** [comment]
@battila7 awesome!! I'm looking forward to seeing this come together :) Fork the starter repo and post the link in here whenever you have a chance & I'll update the issue status 👍

**Comment by EricSimons** [comment]
Created a logo that you can use for the readme in your repo:

![nim](https://cloud.githubusercontent.com/assets/556934/25448342/b9fa5d62-2a7d-11e7-85a5-54d4a77e665c.png)

**Comment by battila7** [comment]
@EricSimons Just forked the repo: [Nim RealWorld](https://github.com/battila7/nim-realworld-example-app)

**Comment by battila7** [comment]
Concluding the experiences of the past two days:

[Real World Nim Adventures](https://medium.com/@bagossyattila/read-world-nim-adventures-5dc85ac7d9d6)

**Comment by EricSimons** [comment]
@battila7 I loved the medium post! Sad to hear you won't have enough time to finish it off :( Should we invite devs to come in & help?

PS - would love to interview you on Thinkster sometime about your experience building the Nim implementation :)

**Comment by battila7** [comment]
@EricSimons I will definitely continue the development, but not be able to dedicate a whole weekend to this project. It'll slow down a little bit but will be finished :)

Sounds like a great opportunity and honor, thanks! We should talk about the details after finishing the implementation, what do you think?

**Comment by EricSimons** [comment]
@battila7 sounds good to me! 👍

**Comment by dom96** [comment]
If you need any assistance feel free to ping me :D

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
