### ISSUE TITLE
🗄🔧 Scala and Playframework

### ISSUE THREAD

**Issue by James-Parsons** [gothinkster/realworld#63]
# Current Status

- ### @James-Parsons will be taking lead on this!
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/scala-play](https://gitter.im/realworld-dev/scala-play)**

### Todo:

- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

I'm planning on doing a Play framework (https://playframework.com) backend in Scala

**Comment by EricSimons** [comment]
@James-Parsons awesome! Just updated issue status w/ gitter room, etc — can you fork the starter kit and post the link to your repo in here?

Also, just created a logo you can use for your repo's readme:

![scala](https://cloud.githubusercontent.com/assets/556934/25451584/460e73ec-2a88-11e7-8fc2-2a15bd0566dd.png)

**Comment by wsargent** [comment]
https://github.com/KyleU/boilerplay may be good as a starting point.  Also see https://github.com/adrianhurt/play-bootstrap for the bootstrap form helpers.

**Comment by ikamthania** [comment]
Is there a plan to include [scalajs-react](https://github.com/japgolly/scalajs-react) frontend?

**Comment by wsargent** [comment]
@ikamthania you may want https://github.com/Daxten/bay-scalajs.g8 in that case

**Comment by James-Parsons** [comment]
Hey guys just a heads up it will likely be a few days before I have time t start on this.

**Comment by ikamthania** [comment]
Hi,
I just created a pull request for the setup [here](https://github.com/James-Parsons/realworld-starter-kit/pull/1) . It is largely inspired from boilerplay with dependency injection using macwire. Do note it includes  a setup for scalajs-react as well but can be removed as required. Do let me know your opinion on it.

**Comment by ikamthania** [comment]
Hi,
I have added home view to the pull request

![home](https://cloud.githubusercontent.com/assets/8693515/25738565/792808dc-319b-11e7-9ee6-e732ca72e15b.png)

Where can I get the favicon from?

**Comment by EricSimons** [comment]
^ ya'll are just creating the backend in Scala to adhere to API spec, right? Or are you also creating a frontend too?

**Comment by ikamthania** [comment]
This setup is mostly for backend in scala. Last commit was just to show that full stack scala is a possibility too. This pr is still open for discussion.

**Comment by yesh0907** [comment]
How's the development for this repo going?

**Comment by johanjvrens** [comment]
Really interested in this! Any progress?

**Comment by EricSimons** [comment]
@yesh0907 @johanjvrens I think these guys ran out of time unfortunately, but lmk if ya'll would like to pick it up & I'll switch the issue to point at your repo!

**Comment by James-Parsons** [comment]
@EricSimons go ahead. I've been ridiculously busy here lately. I'm working three jobs and going back to school so I hardly have the time anymore :/

**Comment by EricSimons** [comment]
@yesh0907 @johanjvrens would either of you like to take lead on this? Lmk and I'll have the issue point to your repo!

**Comment by johanjvrens** [comment]
Thanks, but I don't have time for it.

Kind Regards
Johan Janse van Rensburg

**Comment by Dasiu** [comment]
Hello,

I've started to work on play implementation on my own. It's matter of days or weeks in the worst case, when I would have something, what might be eligible for public view - PRs and introdution for other contributors, so I might be considered as one, who could take lead on this issue/project, if it's ok for everyone of course. :)

I've read that ikamthania implemented something already but given link to repo/PR is not active anymore, so I do not know how to compare - and maybe merge - his work with mine.

I could fork starter repo and post it in few days.

**Comment by Dasiu** [comment]
Here is the link to forked starter kit [repo](https://github.com/Dasiu/realworld-starter-kit) with Play Framework implementation. Right now it has JWT authentication, besides it shows exemplary  project structure and tests. It still needs a lot of work and polishing. I posted the link as an incentive to contribute.

@EricSimons could I pursue this further?

**Comment by Cameron-C-Chapman** [comment]
@Dasiu feel free to continue to work on the Play w/ Scala implementation. We'd love to see it finished and get added to the README!

**Comment by Dasiu** [comment]
All right, folks!

I believe Playframework with Scala implementation have reached feature complete stage! I tested backend implementation with React frontend, link to demo can be found in my [repo](https://github.com/Dasiu/realworld-starter-kit). Now I would ask someone to test my work and review it. People with Scala and Playframework knowledge would be most welcome. :)

**Comment by Dasiu** [comment]
Hey! @Cameron-C-Chapman @EricSimons what is next needed step?

**Comment by EricSimons** [comment]
@Dasiu eek sorry about my delay! Awesome work on this!! I'm going to get this added to the homepage first thing tmrw morn :)

**Comment by EricSimons** [comment]
Now listed on the main readme! Amazing work @Dasiu!! 💯 🎉

**Comment by Dasiu** [comment]
Thanks! Good to hear!
