### ISSUE TITLE
📱🔧 C# on Xamarin

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#70]
# Current Status

- ### @Alonski will be taking lead on this!
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/xamarin](https://gitter.im/realworld-dev/xamarin)**

### Todo:

- [ ] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by Alonski** [comment]
Hmm it seems I can't fork the same repo twice.
Think I should just clone it instead of forking and push to a new repo?

**Comment by lilred** [comment]
Can you please edit the issue name to "C# on Xamarin"? I'd be possibly interested in doing an F# on Xamarin client.

**Comment by EricSimons** [comment]
@lilred done! :)

**Comment by Alonski** [comment]
@EricSimons I didn't realize I didn't tag you earlier. I can't fork the repo again. Think I should just clone it?

**Comment by SandeeshS** [comment]
@Alonski i don't think that would be a problem. Most of us do the same.

**Comment by lestex** [comment]
Hi! Is there any code available for this project?

**Comment by Alonski** [comment]
Hey I never actually found the time to start this :) Good luck

**Comment by EricSimons** [comment]
@lestex lmk if you wanna take over this project

**Comment by SachiraChin** [comment]
@EricSimons @lestex Is someone working on this? Can help or start work on this. I wouldn't be able to finish it real fast though.

**Comment by lestex** [comment]
@SachiraChin seems nobody is, it would be really great if you can start and do the job)

**Comment by EricSimons** [comment]
Yeah totally @SachiraChin, would love to see you start work on this!!

**Comment by federicorinaldi** [comment]
Hey guys is there any update on this? @lestex I can take it if no one is currently working on this

**Comment by DLN-India** [comment]
@federicorinaldi I can take it from where you've left this off, please let me know!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
