### ISSUE TITLE
[Bug tracker] New deployed API

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#712]
A new API is deployed to fix the following issues:
- performance
- NSFW content

This new API is a temporary solution as we can't deploy on the productionready.io domain.
API URL: https://realworld-temp-api.herokuapp.com/api

I chose not to use an existing backend implementation but to create a new one as a starter for the incoming V2.
Please add a comment here if you find any bugs while using this new API.

Bug tracker:

- [ ] GET `/api/articles/feed` doesn't retrieve data as expected
- [x] GET `/api/articles/:slug/comments` response doesn't match the specs format
- [ ] article related tags aren't deleted on cascade when an user deletes an article

**Comment by raulsebastianmihaila** [comment]
@geromegrignon thanks for the temporary API! It seems that login with incorrect credentials fails with a CORS error instead of the expected response.

**Comment by geromegrignon** [comment]
> @geromegrignon thanks for the temporary API! It seems that login with incorrect credentials fails with a CORS error instead of the expected response.

Hello, I just fixed it.

**Comment by raulsebastianmihaila** [comment]
Cool! However it doesn't follow the [spec](https://github.com/gothinkster/realworld/tree/master/api). As is, it breaks the crizmas-mvc implementation. I think the response should be something like:
```
{
  "errors": {
    "email or password": [
      "are incorrect"
    ]
  }
}
```

**Comment by geromegrignon** [comment]
@raulsebastianmihaila fixed too.
I chose to name the key *credentials* : 

```json
{
  "errors": {
    "credentials: [
      "are incorrect"
    ]
  }
}
```

**Comment by Allianzcortex** [comment]
@geromegrignon Hi , a follow-up from morning's `401 authorized` issue . 

- What happened : 

It shows 401 Unauthorized : 

![image](https://user-images.githubusercontent.com/7290780/130495471-38ac6fc9-2258-4da5-a7d0-66886d14a6d6.png)


- Steps to reproduce :  

a. register & login & fetch the feed , so far so good

b. after sometime(I guess JWT expiration time ?) , when trying to refresh the feed , will get the above error 

Token is sent in header : 

![image](https://user-images.githubusercontent.com/7290780/130495707-eb833067-5086-4d75-b273-d64cf0d5e187.png)

**Comment by geromegrignon** [comment]
> @geromegrignon Hi , a follow-up from morning's `401 authorized` issue .
> 
> * What happened :
> 
> It shows 401 Unauthorized :
> 
> ![image](https://user-images.githubusercontent.com/7290780/130495471-38ac6fc9-2258-4da5-a7d0-66886d14a6d6.png)
> 
> * Steps to reproduce :
> 
> a. register & login & fetch the feed , so far so good
> 
> b. after sometime(I guess JWT expiration time ?) , when trying to refresh the feed , will get the above error . If cleaning the token in local storage, then it will work again.
> 
> Token is sent in header :
> 
> ![image](https://user-images.githubusercontent.com/7290780/130495707-eb833067-5086-4d75-b273-d64cf0d5e187.png)

I changed the token duration from 100 minutes to 7 days.
It won't fix the problem but will give me time to prioritize tasks.
I'm not used to developing backend apps and being more used to consume auth on the frontend side than producing one!

**Comment by Allianzcortex** [comment]
> > @geromegrignon Hi , a follow-up from morning's `401 authorized` issue .
> > 
> > * What happened :
> > 
> > It shows 401 Unauthorized :
> > ![image](https://user-images.githubusercontent.com/7290780/130495471-38ac6fc9-2258-4da5-a7d0-66886d14a6d6.png)
> > 
> > * Steps to reproduce :
> > 
> > a. register & login & fetch the feed , so far so good
> > b. after sometime(I guess JWT expiration time ?) , when trying to refresh the feed , will get the above error . If cleaning the token in local storage, then it will work again.
> > Token is sent in header :
> > ![image](https://user-images.githubusercontent.com/7290780/130495707-eb833067-5086-4d75-b273-d64cf0d5e187.png)
> 
> I changed the token duration from 100 minutes to 7 days.
> It won't fix the problem but will give me time to prioritize tasks.
> I'm not used to developing backend apps and being more used to consume auth on the frontend side than producing one!

yet another producer-consumer problem LOLL

**Comment by geromegrignon** [comment]
changed the token duration to 60 days to match the current deployed API :
```ruby
def generate_jwt
    JWT.encode({ id: id,
                 exp: 60.days.from_now.to_i },
               Rails.application.secrets.secret_key_base)
  end
```

**Comment by Allianzcortex** [comment]
@geromegrignon find a issue(should be the last one..)  here. For comment : 

https://github.com/gothinkster/realworld/tree/master/api#single-comment

![image](https://user-images.githubusercontent.com/7290780/130511731-564d22b8-708d-459e-a528-d682b4366806.png)

Here backend should return whole author object instead of `authorId`.

**Comment by geromegrignon** [comment]
@Allianzcortex fixed too. Thanks for reporting it!

**Comment by Allianzcortex** [comment]
@geromegrignon another small issue here :  In old implementation , when we retrieve the feed :  we can get `min(articleCount,500)` value which can help us do pagination

![image](https://user-images.githubusercontent.com/7290780/130830368-74fd6a28-6538-466c-ad7d-cf50f2d20f01.png)


And currently articles count is only the count we return 
![image](https://user-images.githubusercontent.com/7290780/130830496-d096f5d7-fba8-4fcd-a725-2b314d6b885c.png)

**Comment by HoPGoldy** [comment]
@geromegrignon Thank you for providing this api endpoints! I found a bug about `api/articles/{slug}/favorite`:

When request this api, `tagList` in the returned article content become an object array instead of strings array:

![image](https://user-images.githubusercontent.com/28479777/131805379-f0cfd460-fd64-4af2-97eb-9b006d4203ed.png)

**Comment by geromegrignon** [comment]
Hey @HoPGoldy, thanks for reporting it.
It should be fixed by now (for BOTH POST and DELETE on this endpoint).

**Comment by Allianzcortex** [comment]
@geromegrignon seems the register function is losing the temper now ? 

![image](https://user-images.githubusercontent.com/7290780/134267857-2d1b02ab-bb3b-4e2b-a804-0b10c6e2798f.png)

**Comment by geromegrignon** [comment]
@Allianzcortex Thanks!

I made some refactoring to open-source the API source code soon and it resulted in a new bug.
It's now fixed!

**Comment by geromegrignon** [comment]
@raulsebastianmihaila @Allianzcortex the temporary api is now deployed on the original domain: conduit.productionready.io.
You can update the URL of your implementations.

Feel free to provide me feedback

**Comment by Allianzcortex** [comment]
@geromegrignon COOOOOLLL. And also looking forward to the open-source of the new implementation!

**Comment by geromegrignon** [comment]
@Allianzcortex the repository is here: https://github.com/gothinkster/node-express-prisma-v1-official-app
The deployed branch is the `limited` one (with *demo* account, a cron to delete data on a regular basis, and fake data).

**Comment by geromegrignon** [comment]
@raulsebastianmihaila and @Allianzcortex don't waste your time to test conduit.productionready.io for now.

There are some bugs :
conduit.productionready.io being used on an Heroku project we doesn't own, we had to make a redirection through realworld.io

Such a redirection results into cors errors and query params not passed with the redirection.

**Comment by geromegrignon** [comment]
The API now works as expected, I created a PR on repositories using the temporary API.
