### ISSUE TITLE
[V1] API Domain change (discontinued support of conduit.productionready.io)

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#790]
## Description

The current domain used for the demo API is `conduit.productionready.io`.
The current maintainer team doesn't have direct access to this domain and it makes each new maintenance effort on it quite painful (partially explained in #722).

Due to current server redirection, there are inconsistent bugs, for example #788

Currently, `conduit.productionready.io` requests are already redirected to `api.realworld.io`.
I encourage you to use `api.realworld.io`.

## Action

- [ ] change demo API url references in the documentation
- [ ] open pull requests in Frontend accepted Implementations repositories to update them
- [ ] for unmaintained implementations, host an updated version on Netlify to provide a solution for everyone to test them

**Comment by geromegrignon** [comment]
## Open issues in Frontend implementations listed on CodebaseShow

- [ ] [Android native](https://github.com/coding-blocks-archives/Conduit_Android_Kotlin/issues/3)
- [ ] [Android native + Retrofit + Jetpack](https://github.com/Marvel999/Conduit-Android-kotlin/issues/1)
- [ ] [Angular](https://github.com/khaledosman/angular-realworld-example-app/issues/4)
- [ ] [Angular + Ngrx + nx](https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app/issues/69)
- [ ] [AppRun](https://github.com/gothinkster/apprun-realworld-example-app/issues/13)
- [ ] [Aurelia](https://github.com/gothinkster/aurelia-realworld-example-app/issues/63)
- [ ] [Blazor + WebAssembly](https://github.com/JoeyMckenzie/BlazorConduit/issues/8)
- [ ] [crismas-mvc](https://github.com/gothinkster/crizmas-mvc-realworld-example-app/issues)
- [ ] [Dojo](https://github.com/gothinkster/dojo-realworld-example-app/issues/5)
- [ ] [Elm](https://github.com/rtfeldman/elm-spa-example/issues/104)
- [ ] [Ember](https://github.com/gothinkster/ember-realworld/issues/129)
- [x] [Halogen](https://github.com/thomashoneyman/purescript-halogen-realworld/issues/97)
- [ ] [Hoplon](https://github.com/rlander/conduit/issues/6)
- [ ] [Hyperapp](https://github.com/kwasniew/hyperapp-realworld-example-app/issues/16)
- [ ] [Imba](https://github.com/cartonalexandre/imba-realworld-example-app/issues/1)
- [ ] [Keechma](https://github.com/gothinkster/clojurescript-keechma-realworld-example-app/issues/20)
- [x] [Kingly-Svelte](https://github.com/brucou/realworld-kingly-svelte/issues/2)
- [ ] [KVision](https://github.com/rjaros/kvision-realworld-example-app/issues/10)
- [ ] [Mint](https://github.com/mint-lang/mint-realworld/issues/19)
- [ ] [NativeScript](https://github.com/nea/nativescript-realworld-example-app/issues/5)
- [ ] [neo.mjs](https://github.com/neomjs/neomjs-realworld-example-app/issues/3)
- [ ] [Next](https://github.com/reck1ess/next-realworld-example-app/issues/26)
- [ ] [Nuxt](https://github.com/devJang/nuxt-realworld/issues/4)
- [ ] [OWL](https://github.com/Coding-Dodo/owl-realworld-app/issues/30)
- [ ] [Preact](https://github.com/mutoe/preact-realworld-example-app/issues/54)
- [ ] [re-frame](https://github.com/jacekschae/conduit/issues/22)
- [ ] [React + Hooks + Reduc](https://github.com/angelguzmaning/ts-redux-react-realworld-example-app/issues/3)
- [ ] [React + PureScript](https://github.com/jonasbuntinx/purescript-react-realworld/issues/24)
- [ ] [React Native + re-frame](https://github.com/flexsurfer/conduitrn/issues/14)
- [ ] [React + Effector](https://github.com/mg901/effector-react-realworld-example-app/issues/1007)
- [ ] [React + Redux](https://github.com/khaledosman/react-redux-realworld-example-app/issues/7)
- [ ] [React + ReScript](https://github.com/jihchi/rescript-react-realworld-example-app/issues/19)
- [ ] [React + Vite](https://github.com/romansndlr/react-vite-realworld-example-app/issues/28)
- [ ] [Riot](https://github.com/iq3addLi/riot_realworld_example_app/issues/12)
- [ ] [San](https://github.com/ecomfe/san-realworld-app/issues/26)
- [ ] [Seed](https://github.com/seed-rs/seed-rs-realworld/issues/11)
- [ ] [Solid](https://github.com/solidjs/solid-realworld/issues/9)
- [ ] [Stencil](https://github.com/khaledosman/stencil-realworld-app/issues/190)
- [ ] [WebComponents](https://github.com/gothinkster/web-components-realworld-example-app/issues/29)
- [ ] [WebComponents + EventDriven](https://github.com/mits-gossau/event-driven-web-components-realworld-example-app/issues/9)
- [ ] [Vue + Vite](https://github.com/mutoe/vue3-realworld-example-app/issues/75)
- [ ] [Vue + Vuex](https://github.com/khaledosman/vue-realworld-example-app/issues/1)
- [ ] [Vue + Typescript](https://github.com/AlexBrohshtut/vue-ts-realworld-app/issues/23)
- [x] [Wesib](https://github.com/wesib/realworld-app/issues/12)
- [ ] [Yew](https://github.com/jetli/rust-yew-realworld-example-app/issues/24)
