### ISSUE TITLE
📱 🔧 Kotlin/Android

### ISSUE THREAD

**Issue by DrewCarlson** [gothinkster/realworld#84]
# Current Status

* ###  Codebase in progress:<br> [DrewCarlson/realworld-android-kotlin](https://github.com/DrewCarlson/realworld-android-kotlin)

### Todo:
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons)
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

___

So far it just loads the global feed but it's a start! It uses all the fun things like [ReactiveX/RxJava](https://github.com/ReactiveX/RxJava) 2, dependency injection with [SalomonBrys/Kodein](https://github.com/SalomonBrys/Kodein), MVP with [sockeqwe/mosby](https://github.com/sockeqwe/mosby) etc.

**Comment by EricSimons** [comment]
This is awesome!! I can't wait to see this! For the repo's logo, should I just use the android logo? Or both kotlin + android logo?

**Comment by DrewCarlson** [comment]
@EricSimons Good question, I'd say both but I figure someone will make a Java/Android version eventually so if you feel like saving time, just Android would work.

**Comment by EricSimons** [comment]
Here's the logo!

![android](https://cloud.githubusercontent.com/assets/556934/25672246/9a20e960-2fe7-11e7-99d3-23652878a2c2.png)

**Comment by harikautilya** [comment]
i am interested. May i know the starting procedure or should i simply sent you some samples?

**Comment by hadywalied** [comment]
I'm interested, how to start helping 🤓🤓

**Comment by thomkle** [comment]
Has this died out? The linked codebase hasn't had any changes in 17 months. Very much interested in a well implemented clean architecture Android app!

**Comment by championswimmer** [comment]
I have finished this project. https://github.com/coding-blocks-archives/Conduit_Android_Kotlin 

Making a PR to update it to the readme at the front.

**Comment by Marvel999** [comment]
Hello,
I have finished this project. https://github.com/Marvel999/Conduit-Android-kotlin
And made PR update it to the readme at the front.
Please take a look and add my PR.
Thank you
Manish
