### ISSUE TITLE
🗄🔧 CakePHP

### ISSUE THREAD

**Issue by phpnut** [gothinkster/realworld#87]
# Current Status

- ### Codebase in progress:<br /> [gothinkster/cakephp-realworld-example-app](https://github.com/gothinkster/cakephp-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

We would like to implement the backend with CakePHP

We have already forked your starter app here:

https://github.com/CakeDC/cakephp-realworld-example-app

**Comment by phpnut** [comment]
Code pushed, will update readme soon.

**Comment by EricSimons** [comment]
Awesome, I can't wait to see the final version! I also just created a logo that you can use for the repo:

![cake](https://cloud.githubusercontent.com/assets/556934/25641152/74232624-2f47-11e7-84cb-d02baf75666b.png)

**Comment by skie** [comment]
Task list categorized by api

- [x] Articles
   - [x]  GET - Feed
   - [x]  GET - All articles
   - [x]  GET - Articles by author
   - [x]  GET - Articles favorited by username
   - [x]  GET - Articles by tag
   - [x]  POST - Create article
   - [x]  GET - Single article by slug
   - [x]  DEL - Delete article
   - [x]  PUT - Update article
   - [x]  POST - Favorite article
   - [x]  DEL - Unfavorite article

- [x] Auth
   - [x]  POST - Login
   - [x]  POST - Login and remember token
   - [x]  POST - Register
   - [x]  GET - Get current user
   - [x]  PUT - Update user

- [x] Comments
   - [x]  GET - All comments for article
   - [x]  POST - Create comment for article
   - [x]  DEL - Delete comment

- [x] Profile
   - [x]  GET - Profile
   - [x]  POST - Follow profile
   - [x]  DEL - Unfollow profile

- [x] Tags
   - [x]  GET - Get all tags

**Comment by phpnut** [comment]
@EricSimons The API is implemented and ready for peer review.

**Comment by brwr** [comment]
One thing I noticed is that MySQL is being used. I think MySQL is more common than PostgreSQL in the PHP community. Feel free to correct me if I'm wrong.

@EricSimons Do we have standards around which database should be chosen? Should database setup documentation be included in the repository?

**Comment by brwr** [comment]
Also, it looks like there is some generated code that can be removed. See [src/Controller/PagesController.php](https://github.com/CakeDC/cakephp-realworld-example-app/blob/master/src/Controller/PagesController.php).

My knowledge of PHP is limited, so feel free to correct me on anything I'm wrong about.

**Comment by EricSimons** [comment]
@brwr no — we let the author choose the desired DB.

**Comment by EricSimons** [comment]
@phpnut great work! Have you tried pointing one of our frontend implementations at this backend to see if it works? Often times CORS will manually need to be enabled, etc.  (btw I'm attempting to get this to run locally, but running into PHP ini issues)

**Comment by skie** [comment]
I don't see any database requirements. But cakephp can work with any database: both MySQL and Postgress are fully supported.

**Comment by skie** [comment]
@EricSimons I've tested with angluar2 and react frontends. Both was working really nice.

**Comment by phpnut** [comment]
The CakePHP ORM works with many databases, the user can choose whatever they want. The migrations setup will setup the tables as needed.

 Drivers include Mysql Postgres Sqlite Sqlserver

**Comment by phpnut** [comment]
@EricSimons what errors are you getting? Is it related to intl extension?

**Comment by EricSimons** [comment]
@phpnut yup that's the one — any idea how to fix? (I'm a PHP noob :)

**Comment by phpnut** [comment]
@EricSimons you need to have intl extension installed and enabled to use CakePHP. What OS are you using?

**Comment by EricSimons** [comment]
@phpnut Mac 10.12.1

**Comment by phpnut** [comment]
@EricSimons ok, this is not compiled by default. MAMP for Mac has intl active by default, this would be the quickest way to download and test. If you would like to install intl extension on your vanilla php install on the Mac I can provide you with some steps to do this.

I am currently working on a plugin that can replicate the functionality CakePHP using for translations and other features, but life has thrown some blockers. I plan to start on it again soon.

**Comment by EricSimons** [comment]
@phpnut okay perfect, will try out MAMP and see if that works :)

In the meantime, if there are any other CakePHP folks out there who can review the code and 👍  or 👎  that would be great!

**Comment by phpnut** [comment]
@EricSimons, that would be great. We kinda make a living reviewing CakePHP code for others :)

**Comment by SandeeshS** [comment]
I'll give this a test on my end as well.

**Comment by SandeeshS** [comment]
Looks like CakePHP hates windows setup. I got it running fairly easily on a vagrant box. But the instructions are clearly lacking for a beginner. What are the api routes? I'm getting an error on accessing http://cake.dev/api/articles or any url. The error message is "Extension class OptionsHandlerExtension could not be found."

**Comment by phpnut** [comment]
What problems did you have with windows?

**Comment by skie** [comment]
@SandeeshS it works on windows well as it was developed and tested there. There was old composer.lock file. Please pull and run "composer install" again.

**Comment by SandeeshS** [comment]
@skie seems like the pull fixed it, got the api working fine now :+1: It's 1:30am here and i'm about to hit d bed. I'll do a thorough test in the morning and leave my feedback. Although at first glance there seem to be additional data coming through the api, like the tags count on tag, additional pagination info on articles.

**Comment by skie** [comment]
> Although at first glance there seem to be additional data coming through the api, like the tags count on tag, additional pagination info on articles.
Pagniation and tags count info is removed from response.

**Comment by dereuromark** [comment]
I think you should remove all empty (noise) folders, makes people easier to focus on the actual code inside the repo

e.g.

- https://github.com/CakeDC/cakephp-realworld-example-app/tree/master/plugins
- https://github.com/CakeDC/cakephp-realworld-example-app/tree/master/src/View/Helper
- https://github.com/CakeDC/cakephp-realworld-example-app/tree/master/src/Controller/Component
- https://github.com/CakeDC/cakephp-realworld-example-app/tree/master/src/Model/Behavior

etc.

**Comment by phpnut** [comment]
> Also, it looks like there is some generated code that can be removed. See src/Controller/PagesController.php.

@brwr This is used by the default route if someone was to visit / vs /api so it is needed

**Comment by phpnut** [comment]
@EricSimons all unused directories and files removed. You can fork the project back to your GitHub account now.

**Comment by EricSimons** [comment]
Official repo is online at https://github.com/gothinkster/cakephp-realworld-example-app and @phpnut and @skie have been added as collborators :)

**Comment by phpnut** [comment]
@EricSimons Thanks, glad to see your project and can see it being very useful to people looking at different tools to develop their apps with. Nice way to compare, create work.

Are you going to be able to change the gif? media/stacks_hr.gif

**Comment by EricSimons** [comment]
@phpnut it's actually a screencap of our animation on https://thinkster.io :) I need to split it out and make it easily expandable, but yes absolutely I'll include CakePHP in there once I find a few minutes to do that!

Now that this repo is in the main org, I'm gonna go ahead and close this issue. Thanks again for the amazing work CakePHP folks!

**Comment by phpnut** [comment]
@EricSimons you can use this SVG, it you need another format let me know.

https://cakephp.org/v2/img/logos/CakePHP_Logo.svg
