### ISSUE TITLE
🗄🔧 ASP.NET Core

### ISSUE THREAD

**Issue by adamhathcock** [gothinkster/realworld#89]
# Current Status

* Codebase in progress:
 https://github.com/adamhathcock/realworld-aspnetcore-kit

## Todo:
- [x]  🏁 Fork the starter repo & post the link in this issue 
- [x]  🎨 Create logo for repo & update issue status (@ericsimons)
- [x]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ]  🎉 Tag v1 release, move repo to main org, and officially list it on the README!

## Get involved!:
- Help implement more of the REST API spec: https://github.com/adamhathcock/realworld-aspnetcore-kit/issues/1
- Suggest items for the overall checklist: https://github.com/adamhathcock/realworld-aspnetcore-kit/issues/4
- Complete issues via Pull Requests or more add issues! https://github.com/adamhathcock/realworld-aspnetcore-kit/issues

## Background
This was done as the other Dotnet Core project https://github.com/gothinkster/realworld/issues/31 isn't a good showcase for the usage of features or speed of creating the Conduit backend.  Look at the [README](https://github.com/adamhathcock/realworld-aspnetcore-kit/blob/master/readme.md) for more info!

**Comment by EricSimons** [comment]
Feel free to use the same logo as the C# version btw :)

**Comment by brwr** [comment]
Have you considered working with @abauzac on #31? 

It sounds like you're not happy with the approach @abauzac has taken. Have you tried opening an issue to raise these concerns?

We don't want two have multiple implementations for the same stack if we can avoid it. After all, we're here to help people who are learning ASP.NET Core. Having multiple implementations is more likely to confuse them than it is to help.

**Comment by adamhathcock** [comment]
I did try but it seems the basic aims are different https://github.com/abauzac/realworld-netcore-kit/issues/9

**Comment by adamhathcock** [comment]
Logo updated!

I'm intentionally moving a bit slow to ensure if anyone wants to help.  I have most of the infrastructure ready, including JWT.

**Comment by adamhathcock** [comment]
@EricSimons I think I've completed.  Been testing with the React frontend.

**Comment by EricSimons** [comment]
Okay, I've got this marked as RFC! Are there any ASP.NET folks out there who can review this codebase?

**Comment by EricSimons** [comment]
@adamhathcock just created the official repo and added you as a collab/admin on it (https://github.com/gothinkster/aspnetcore-realworld-example-app) — great job! 👍 💯 

Closing this issue; future issues should be opened up on the offical repo directly -> https://github.com/gothinkster/aspnetcore-realworld-example-app/issues

**Comment by adamhathcock** [comment]
Awesome, thanks!

**Comment by Stephn-R** [comment]
@adamhathcock @EricSimons I would gladly like to see how well this was built. I am sure it is out of this world 👍 haha

**Comment by adamhathcock** [comment]
It's there and ready.  Suggestions and additions are welcome.
