### ISSUE TITLE
🗄🔧 Dropwizard

### ISSUE THREAD

**Issue by Kevenvz** [gothinkster/realworld#95]
# Current Status

- ### Codebase in progress: [Kevenvz/realworld-dropwizard-kit](https://github.com/Kevenvz/realworld-dropwizard-kit)
- ### Interested in helping out? Say hello! 🎉

### Todo:
- [X]  🏁 Fork the starter repo & post the link in this issue
- [x]  🎨 Create logo for repo & update issue status (@ericsimons)
- [ ]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

---

I really like dropwizard as a framework to create API's with. Since it's not a super popular framework there aren't many example API's out there and I'd like to contribute to RealWorld to show the power and simplicity of Dropwizard applications.

**Comment by EricSimons** [comment]
Awesome! Here's a logo that you can use for your readme:

![dropwizard](https://cloud.githubusercontent.com/assets/556934/25719383/1ad840ae-30be-11e7-9d4b-6604f8487a72.png)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
