### ISSUE TITLE
📱 Native Script

### ISSUE THREAD

**Issue by SuperlativeEntity** [gothinkster/realworld#96]
# Current Status

- ### Codebase in progress:<br /> [https://github.com/mkoczka/nativescript-realworld-example-app](https://github.com/mkoczka/nativescript-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by EricSimons** [comment]
Any NativeScript devs out there who'd want to take this on? :)

**Comment by mkoczka** [comment]
@EricSimons I can start working on this one.

https://github.com/mkoczka/nativescript-realworld-example-app

**Comment by EricSimons** [comment]
@mkoczka awesome, I can't wait to see this one! Lmk if you have any q's/etc :) I just updated the issue to point at your repo & created a logo you can use:

![rw_ns](https://user-images.githubusercontent.com/556934/34134611-7c390e90-e410-11e7-95fb-25ee73dc1d9b.png)

**Comment by Cameron-C-Chapman** [comment]
#221 looks like our first NativeScript implementation! I'll close this for now and let anyone who wants to implement in anything other than Angular open a new PR at the time.
