### ISSUE TITLE
[Feature Request]: SVG icon

### ISSUE THREAD

**Issue by DanielRamosAcosta** [gothinkster/realworld#982]
### Relevant Scope

Frontend specs

### Description

I've see that in the [media](https://github.com/gothinkster/realworld/tree/main/media) directory are several sizes of the Real World icon, but are there any SVG?

### Describe the solution you'd like

A SVG icon version

### Describe alternatives you've considered

🤷🏽‍♂️

**Comment by geromegrignon** [comment]
Hi @DanielRamosAcosta,
Sadly when the current maintenance team joined the project, the original assets were already lost.

**Comment by DanielRamosAcosta** [comment]
Oh, thanks for the response @geromegrignon

**Comment by geromegrignon** [comment]
# 💭 Introduction

We need a svg version of our logo.
![realworld-logo](https://user-images.githubusercontent.com/32737308/193610471-738e8766-e6d9-4b5d-bbe2-74cc350554d0.png)

# ✏️ Task

- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned.
- [ ] create an SVG version of the current logo (the png version is available [here](https://github.com/gothinkster/realworld/blob/main/media/realworld-logo.png)
- [ ] Submit a pull request

**Comment by Vishal2002** [comment]
Do you need to convert the current logo from PNG to SVG .

**Comment by geromegrignon** [comment]
Hi @Vishal2002, exactly!

**Comment by Vishal2002** [comment]
Assign me this issue to work on

**Comment by geromegrignon** [comment]
sure, done. Thanks for your help.

**Comment by Vishal2002** [comment]
Where I have to add the SVG file Can you tell me?

**Comment by geromegrignon** [comment]
You can add it in the [media folder](https://github.com/gothinkster/realworld/tree/main/media), naming it **realworld-logo.svg**.

**Comment by Vishal2002** [comment]
Will this issue get counted in the hacktoberfest?

**Comment by geromegrignon** [comment]
sure I really appreciate the help and will apply the label on it (I don't put it on the project directly to avoid some spam).

**Comment by Vishal2002** [comment]
I am unable to see the change on the dashboard of hacktoberfest.

**Comment by geromegrignon** [comment]
Hi @Vishal2002, the label must be applied on the Pull Request, but you didn't submit one yet to the project.

**Comment by geromegrignon** [comment]
I looked at the file in your fork (https://github.com/Vishal2002/realworld/blob/main/media/realworld-logo%20(2).svg), and that's an inverted image, so it doesn't fit the requirement. By using it, the logo would be transparent with a black background.

**Comment by Openegg15** [comment]
This is a follow-up to [#1822](https://rausauboocad.net/4/7446717) and [#100 ](https://tremblesyringeillusive.com/ne8muthq4i?key=474c9752b6833707c410d6e7be2d821f)

**Comment by DanielRamosAcosta** [comment]
It took me two years, but finally I did it haha, fixed in #1550

**Comment by c4ffein** [comment]
Thanks for the contribution, unfortunately the logo app has just been updated to look slightly more modern, directly in svg
